### ISSUE TITLE
Error when non-ascii char in gff file

### ISSUE THREAD

**Issue by abretaud** [askomics/askomics#173] opened 2017-05-29 12:34 UTC
I'm thinking back about the error we got last week when importnig a file containing an epsilon char.
I managed to load it by modifying the gff file like this:

`cat clec_OGS_v1_2_dl.gff3 | iconv -f utf-8 -t ascii//translit > clec_OGS_v1_2.gff3`

But it would be much better if askomics could handle it without modifying the input file

Example problematic file: https://i5k.nal.usda.gov/sites/default/files/data/Arthropoda/cimlec-%28Cimex_lectularius%29/Current%20Genome%20Assembly/2.Official%20or%20Primary%20Gene%20Set/OGS_v1_2/clec_OGS_v1_2.gff3.gz

**Comment by xgaia** [comment] 2017-07-05 12:40
Hello AskoTeam! I can't reproduce the error, anyone has corrected this ?

**Comment by abretaud** [comment] 2017-07-05 14:55
Hello Xavier
I have no idea, did you try with the buggy gff3?
Good welsh!

**Comment by xgaia** [comment] 2017-07-06 08:12
Yes, and the file is well integrated.

**Comment by abretaud** [comment] 2017-07-06 08:14
interesting... I'll check this on my setup and close this if it's solved

**Comment by xgaia** [comment] 2017-09-28 08:53
I close the issue because i can't reproduce the bug. Reopen if you have the problem again

**Closed by xgaia** 2017-09-28 08:53 UTC
